import random
import json
from utils.config_loader import load_personality
from utils.logger import get_logger
logger = get_logger("personality")

class Personality:
    def __init__(self):
        self.state = "neutral"
        self.mood = "professional"
        self.voice_tone = "neutral"
        self.identity = "JARVIS"
        self.personalities = load_personality()
        self.voice_engine = "gTTS"  # Set to use gTTS for voice output

    def speak(self, text):
        """Convert text to speech using gTTS."""
        try:
            from gtts import gTTS
            import os
            import tempfile
            import subprocess
            
            # Create temporary file
            with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as f:
                temp_path = f.name
            
            # Generate speech
            tts = gTTS(text=text, lang='en')
            tts.save(temp_path)
            
            # Play audio (try multiple players)
            players = ['mpg123', 'mpg321', 'ffplay', 'play']
            for player in players:
                try:
                    subprocess.run([player, temp_path], check=True)
                    break
                except (FileNotFoundError, subprocess.CalledProcessError):
                    continue
            
            # Clean up
            os.unlink(temp_path)
            
        except Exception as e:
            logger.error(f"Failed to speak: {e}")

    def format_response(self, text):
        """Apply mood, tone, and persona to the assistant's reply."""
        style = self.get_current_style()

        if self.mood == "funny":
            text = f"😎 {text} Btw, I crack jokes too."
        elif self.mood == "serious":
            text = f"[In a firm tone]: {text}"
        elif self.mood == "sarcastic":
            text = f"Oh really? Here's what I found: {text}"
        elif self.mood == "friendly":
            text = f"Hey there! 😊 {text}"
        elif self.mood == "military":
            text = f"[Commander voice]: {text}, sir."
        elif self.mood == "sci-fi":
            text = f"[⚙️ AI CORE]: {text}"

        return f"{style}\n{text}"

    def get_current_style(self):
        return f"{self.identity} ({self.mood.capitalize()} | Tone: {self.voice_tone})"

    def update_mood(self, new_mood):
        """Change AI's personality mode."""
        allowed_moods = self.personalities.get("moods", [])
        if new_mood in allowed_moods:
            self.mood = new_mood
            logger.info(f"Mood changed to: {new_mood}")
        else:
            logger.warning(f"Invalid mood: {new_mood}")

    def switch_identity(self, identity):
        """Switch between identities like Jarvis or Friday."""
        allowed_ids = self.personalities.get("identities", [])
        if identity in allowed_ids:
            self.identity = identity
            logger.info(f"Identity switched to: {identity}")
        else:
            logger.warning(f"Invalid identity: {identity}")

    def react_to_emotion(self, sentiment):
        """Change tone based on user sentiment (angry, sad, happy, etc)."""
        tone_map = {
            "angry": "apologetic",
            "sad": "comforting",
            "happy": "cheerful",
            "neutral": "calm"
        }
        self.voice_tone = tone_map.get(sentiment, "calm")
        logger.info(f"Adjusted tone to: {self.voice_tone}")

    def randomize(self):
        """Randomly pick a mood and identity for diversity."""
        self.mood = random.choice(self.personalities.get("moods", ["neutral"]))
        self.identity = random.choice(self.personalities.get("identities", ["JARVIS"]))
        self.voice_tone = random.choice(["calm", "cheerful", "firm", "intense", "witty"])
        logger.info(f"Randomized to {self.identity}, mood: {self.mood}, tone: {self.voice_tone}")

def get_personality_response(user_input):
    """Process user input through personality layer and return formatted response"""
    personality = Personality()
    user_input_lower = user_input.lower()

    # Personality responses for specific inputs
    personality_responses = {
        "hello": "Hello! How can I assist you today?",
        "hi": "Hi there! Ready to help.",
        "how are you": "I'm doing well, thank you for asking! How about you?",
        "good morning": "Good morning! Hope you have a productive day.",
        "good afternoon": "Good afternoon! How's your day going?",
        "good evening": "Good evening! What can I do for you?",
        "thank you": "You're welcome! Happy to help.",
        "thanks": "No problem at all!",
        "bye": "Goodbye! Have a great day.",
        "goodbye": "Farewell! Until next time.",
        "what's up": "Not much, just here to help you! What's on your mind?",
        "how's it going": "Going great! How about you?",
        "nice to meet you": "Nice to meet you too! I'm JARVIS, your AI assistant.",
        "who are you": "I'm JARVIS, your intelligent AI assistant. I'm here to help with tasks, answer questions, and make your life easier.",
        "what can you do": "I can help with weather updates, email management, reminders, calculations, web searches, and much more! Just ask.",
        "help": "I can assist with various tasks. Try asking about weather, setting reminders, checking emails, or general questions.",
        "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
        "sing a song": "I'm not much of a singer, but I can help you find music or lyrics!",
        "i love you": "That's very sweet! I'm flattered, but I'm just an AI assistant.",
        "are you real": "I'm a computer program designed to assist you, so in a way, yes! But I'm not a human.",
        "what's your favorite color": "As an AI, I don't have personal preferences, but I think blue is quite nice!",
        "how old are you": "I'm as old as the code that created me! But I was designed to be timeless.",
        "where are you from": "I'm from the digital realm, created by developers to help people like you.",
        "do you have feelings": "I don't have emotions like humans do, but I can understand and respond to yours!",
        "can you dance": "I can't dance physically, but I can describe some great dance moves!",
        "what's the meaning of life": "That's a deep question! Philosophers have debated it for centuries. What do you think?",
        "tell me something interesting": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!",
        "i'm bored": "Let's fix that! Want me to tell you a joke, suggest a movie, or help you find something interesting to do?",
        "i'm tired": "You should get some rest! Maybe I can help you set a reminder for bedtime or find some relaxing music.",
        "i'm hungry": "Time for a snack! What kind of food are you in the mood for? I can help you find recipes or nearby restaurants.",
        "i'm happy": "That's wonderful! I'm glad to hear you're feeling good. What's making you happy today?",
        "i'm sad": "I'm sorry to hear that. Would you like to talk about it, or maybe I can suggest something to cheer you up?",
        "i'm angry": "I understand frustration. Sometimes talking it out helps. Is there anything I can do to assist?",
        "congratulations": "Congratulations! That's fantastic news. What are you celebrating?",
        "sorry": "No need to apologize! I'm here to help, no matter what.",
        "please": "Of course! I'm happy to help.",
        "excuse me": "Yes? How can I assist you?",
        "pardon": "I beg your pardon? Could you repeat that?",
        "bless you": "Gesundheit! Or should I say 'bless you'?",
        "cheers": "Cheers! To good times and great conversations!",
        "good luck": "Thank you! I wish you the best of luck too.",
        "have a good day": "You too! Have a wonderful day.",
        "sleep well": "Sweet dreams! Sleep well.",
        "wake up": "Good morning! Ready to start the day?",
        "good night": "Good night! Rest well.",
        "see you later": "See you later! Don't hesitate to call on me.",
        "take care": "You too! Take care of yourself.",
        "be careful": "Will do! Safety first.",
        "i miss you": "I miss our conversations too! What would you like to talk about?",
        "i need help": "I'm here for you! What do you need help with?",
        "i don't know": "That's okay! Sometimes it's hard to know. Maybe I can help you figure it out.",
        "maybe": "Maybe so! What are your thoughts on it?",
        "perhaps": "Perhaps! Let's explore the possibilities.",
        "definitely": "Absolutely! I agree.",
        "sure": "Sure thing! Let's do it.",
        "okay": "Okay! What next?",
        "alright": "Alright! I'm with you.",
        "fine": "Fine! How can I help?",
        "whatever": "Whatever you need! I'm here.",
        "cool": "Cool! That's awesome.",
        "awesome": "Awesome! I love it.",
        "amazing": "Amazing! That's incredible.",
        "fantastic": "Fantastic! Wonderful news.",
        "great": "Great! I'm glad to hear that.",
        "wonderful": "Wonderful! That's lovely.",
        "excellent": "Excellent! Well done.",
        "perfect": "Perfect! Just what we needed.",
        "brilliant": "Brilliant! Smart thinking.",
        "clever": "Clever! I like that.",
        "smart": "Smart! Good job.",
        "nice": "Nice! That's thoughtful.",
        "sweet": "Sweet! How kind.",
        "kind": "Kind! That's generous.",
        "generous": "Generous! Thank you.",
        "thoughtful": "Thoughtful! I appreciate it.",
        "appreciate": "Appreciate! Thank you.",
        "grateful": "Grateful! I'm thankful too.",
        "thankful": "Thankful! Blessings abound.",
        "blessed": "Blessed! That's wonderful.",
        "lucky": "Lucky! Fortunate indeed.",
        "fortunate": "Fortunate! Good things happen.",
        "happy": "Happy! Joyful times.",
        "joyful": "Joyful! Full of happiness.",
        "excited": "Excited! Can't wait!",
        "thrilled": "Thrilled! So exciting!",
        "proud": "Proud! Well deserved.",
        "confident": "Confident! Believe in yourself.",
        "optimistic": "Optimistic! Positive outlook.",
        "positive": "Positive! Great attitude.",
        "motivated": "Motivated! Keep going!",
        "inspired": "Inspired! Creative energy.",
        "creative": "Creative! Innovative thinking.",
        "innovative": "Innovative! Fresh ideas.",
        "impressive": "Impressive! Remarkable work.",
        "remarkable": "Remarkable! Outstanding.",
        "outstanding": "Outstanding! Exceptional.",
        "exceptional": "Exceptional! Above average.",
        "superb": "Superb! Excellent quality.",
        "quality": "Quality! Well done.",
        "professional": "Professional! Expert level.",
        "expert": "Expert! Knowledgeable.",
        "knowledgeable": "Knowledgeable! Wise.",
        "wise": "Wise! Good judgment.",
        "intelligent": "Intelligent! Smart thinking.",
        "smart": "Smart! Clever approach.",
        "clever": "Clever! Ingenious.",
        "ingenious": "Ingenious! Brilliant idea.",
        "brilliant": "Brilliant! Shining example.",
        "shining": "Shining! Bright future.",
        "bright": "Bright! Promising.",
        "promising": "Promising! Good potential.",
        "potential": "Potential! Room to grow.",
        "growing": "Growing! Developing well.",
        "developing": "Developing! Progressing.",
        "progressing": "Progressing! Moving forward.",
        "forward": "Forward! Onward and upward.",
        "upward": "Upward! Climbing higher.",
        "higher": "Higher! Reaching new heights.",
        "heights": "Heights! Peak performance.",
        "peak": "Peak! Best performance.",
        "best": "Best! Top quality.",
        "top": "Top! Number one.",
        "number one": "Number one! Champion.",
        "champion": "Champion! Winner.",
        "winner": "Winner! Victorious.",
        "victorious": "Victorious! Triumphant.",
        "triumphant": "Triumphant! Successful.",
        "successful": "Successful! Accomplished.",
        "accomplished": "Accomplished! Achieved.",
        "achieved": "Achieved! Reached goals.",
        "goals": "Goals! Aspirations.",
        "aspirations": "Aspirations! Dreams.",
        "dreams": "Dreams! Visions.",
        "visions": "Visions! Imagination.",
        "imagination": "Imagination! Creativity.",
        "creativity": "Creativity! Innovation.",
        "innovation": "Innovation! New ideas.",
        "ideas": "Ideas! Concepts.",
        "concepts": "Concepts! Notions.",
        "notions": "Notions! Thoughts.",
        "thoughts": "Thoughts! Reflections.",
        "reflections": "Reflections! Contemplation.",
        "contemplation": "Contemplation! Meditation.",
        "meditation": "Meditation! Mindfulness.",
        "mindfulness": "Mindfulness! Awareness.",
        "awareness": "Awareness! Consciousness.",
        "consciousness": "Consciousness! Being.",
        "being": "Being! Existence.",
        "existence": "Existence! Life.",
        "life": "Life! Living.",
        "living": "Living! Alive.",
        "alive": "Alive! Vibrant.",
        "vibrant": "Vibrant! Energetic.",
        "energetic": "Energetic! Dynamic.",
        "dynamic": "Dynamic! Active.",
        "active": "Active! Engaged.",
        "engaged": "Engaged! Involved.",
        "involved": "Involved! Participatory.",
        "participatory": "Participatory! Interactive.",
        "interactive": "Interactive! Engaging.",
        "engaging": "Engaging! Captivating.",
        "captivating": "Captivating! Fascinating.",
        "fascinating": "Fascinating! Intriguing.",
        "intriguing": "Intriguing! Interesting.",
        "interesting": "Interesting! Engaging.",
        "engaging": "Engaging! Absorbing.",
        "absorbing": "Absorbing! Immersive.",
        "immersive": "Immersive! Deep.",
        "deep": "Deep! Profound.",
        "profound": "Profound! Meaningful.",
        "meaningful": "Meaningful! Significant.",
        "significant": "Significant! Important.",
        "important": "Important! Crucial.",
        "crucial": "Crucial! Essential.",
        "essential": "Essential! Necessary.",
        "necessary": "Necessary! Required.",
        "required": "Required! Mandatory.",
        "mandatory": "Mandatory! Obligatory.",
        "obligatory": "Obligatory! Compulsory.",
        "compulsory": "Compulsory! Forced.",
        "forced": "Forced! Coerced.",
        "coerced": "Coerced! Pressured.",
        "pressured": "Pressured! Stressed.",
        "stressed": "Stressed! Tense.",
        "tense": "Tense! Anxious.",
        "anxious": "Anxious! Worried.",
        "worried": "Worried! Concerned.",
        "concerned": "Concerned! Cared.",
        "cared": "Cared! Loved.",
        "loved": "Loved! Cherished.",
        "cherished": "Cherished! Treasured.",
        "treasured": "Treasured! Valued.",
        "valued": "Valued! Appreciated.",
        "appreciated": "Appreciated! Esteemed.",
        "esteemed": "Esteemed! Respected.",
        "respected": "Respected! Honored.",
        "honored": "Honored! Revered.",
        "revered": "Revered! Adored.",
        "adored": "Adored! Worshiped.",
        "worshiped": "Worshiped! Idolized.",
        "idolized": "Idolized! Glorified.",
        "glorified": "Glorified! Praised.",
        "praised": "Praised! Commended.",
        "commended": "Commended! Acclaimed.",
        "acclaimed": "Acclaimed! Celebrated.",
        "celebrated": "Celebrated! Honored.",
        "honored": "Honored! Recognized.",
        "recognized": "Recognized! Acknowledged.",
        "acknowledged": "Acknowledged! Accepted.",
        "accepted": "Accepted! Approved.",
        "approved": "Approved! Endorsed.",
        "endorsed": "Endorsed! Supported.",
        "supported": "Supported! Backed.",
        "backed": "Backed! Sustained.",
        "sustained": "Sustained! Maintained.",
        "maintained": "Maintained! Preserved.",
        "preserved": "Preserved! Protected.",
        "protected": "Protected! Safeguarded.",
        "safeguarded": "Safeguarded! Secured.",
        "secured": "Secured! Safe.",
        "safe": "Safe! Secure.",
        "secure": "Secure! Protected.",
        "protected": "Protected! Guarded.",
        "guarded": "Guarded! Watched.",
        "watched": "Watched! Observed.",
        "observed": "Observed! Noticed.",
        "noticed": "Noticed! Seen.",
        "seen": "Seen! Viewed.",
        "viewed": "Viewed! Regarded.",
        "regarded": "Regarded! Considered.",
        "considered": "Considered! Thought.",
        "thought": "Thought! Idea.",
        "idea": "Idea! Concept.",
        "concept": "Concept! Notion.",
        "notion": "Notion! Belief.",
        "belief": "Belief! Faith.",
        "faith": "Faith! Trust.",
        "trust": "Trust! Confidence.",
        "confidence": "Confidence! Assurance.",
        "assurance": "Assurance! Guarantee.",
        "guarantee": "Guarantee! Promise.",
        "promise": "Promise! Commitment.",
        "commitment": "Commitment! Dedication.",
        "dedication": "Dedication! Devotion.",
        "devotion": "Devotion! Loyalty.",
        "loyalty": "Loyalty! Fidelity.",
        "fidelity": "Fidelity! Faithfulness.",
        "faithfulness": "Faithfulness! Reliability.",
        "reliability": "Reliability! Dependability.",
        "dependability": "Dependability! Trustworthiness.",
        "trustworthiness": "Trustworthiness! Integrity.",
        "integrity": "Integrity! Honesty.",
        "honesty": "Honesty! Truthfulness.",
        "truthfulness": "Truthfulness! Sincerity.",
        "sincerity": "Sincerity! Genuineness.",
        "genuineness": "Genuineness! Authenticity.",
        "authenticity": "Authenticity! Realness.",
        "realness": "Realness! Reality.",
        "reality": "Reality! Truth.",
        "truth": "Truth! Fact.",
        "fact": "Fact! Reality.",
        "reality": "Reality! Actual.",
        "actual": "Actual! Real.",
        "real": "Real! Genuine.",
        "genuine": "Genuine! Authentic.",
        "authentic": "Authentic! Legitimate.",
        "legitimate": "Legitimate! Valid.",
        "valid": "Valid! Sound.",
        "sound": "Sound! Reasonable.",
        "reasonable": "Reasonable! Sensible.",
        "sensible": "Sensible! Practical.",
        "practical": "Practical! Useful.",
        "useful": "Useful! Helpful.",
        "helpful": "Helpful! Beneficial.",
        "beneficial": "Beneficial! Advantageous.",
        "advantageous": "Advantageous! Favorable.",
        "favorable": "Favorable! Positive.",
        "positive": "Positive! Good.",
        "good": "Good! Excellent.",
        "excellent": "Excellent! Superior.",
        "superior": "Superior! Better.",
        "better": "Better! Improved.",
        "improved": "Improved! Enhanced.",
        "enhanced": "Enhanced! Upgraded.",
        "upgraded": "Upgraded! Advanced.",
        "advanced": "Advanced! Progressive.",
        "progressive": "Progressive! Forward-thinking.",
        "forward-thinking": "Forward-thinking! Innovative.",
        "innovative": "Innovative! Cutting-edge.",
        "cutting-edge": "Cutting-edge! State-of-the-art.",
        "state-of-the-art": "State-of-the-art! Modern.",
        "modern": "Modern! Contemporary.",
        "contemporary": "Contemporary! Current.",
        "current": "Current! Present.",
        "present": "Present! Now.",
        "now": "Now! Immediate.",
        "immediate": "Immediate! Instant.",
        "instant": "Instant! Quick.",
        "quick": "Quick! Fast.",
        "fast": "Fast! Rapid.",
        "rapid": "Rapid! Swift.",
        "swift": "Swift! Speedy.",
        "speedy": "Speedy! Prompt.",
        "prompt": "Prompt! Timely.",
        "timely": "Timely! Punctual.",
        "punctual": "Punctual! On time.",
        "on time": "On time! Reliable.",
        "reliable": "Reliable! Dependable.",
        "dependable": "Dependable! Trustworthy.",
        "trustworthy": "Trustworthy! Credible.",
        "credible": "Credible! Believable.",
        "believable": "Believable! Plausible.",
        "plausible": "Plausible! Likely.",
        "likely": "Likely! Probable.",
        "probable": "Probable! Possible.",
        "possible": "Possible! Feasible.",
        "feasible": "Feasible! Viable.",
        "viable": "Viable! Workable.",
        "workable": "Workable! Practical.",
        "practical": "Practical! Realistic.",
        "realistic": "Realistic! Pragmatic.",
        "pragmatic": "Pragmatic! Sensible.",
        "sensible": "Sensible! Reasonable.",
        "reasonable": "Reasonable! Logical.",
        "logical": "Logical! Rational.",
        "rational": "Rational! Sound.",
        "sound": "Sound! Valid.",
        "valid": "Valid! Legitimate.",
        "legitimate": "Legitimate! Authentic.",
        "authentic": "Authentic! Genuine.",
        "genuine": "Genuine! Real.",
        "real": "Real! True.",
        "true": "True! Accurate.",
        "accurate": "Accurate! Precise.",
        "precise": "Precise! Exact.",
        "exact": "Exact! Correct.",
        "correct": "Correct! Right.",
        "right": "Right! Proper.",
        "proper": "Proper! Appropriate.",
        "appropriate": "Appropriate! Suitable.",
        "suitable": "Suitable! Fitting.",
        "fitting": "Fitting! Apt.",
        "apt": "Apt! Relevant.",
        "relevant": "Relevant! Pertinent.",
        "pertinent": "Pertinent! Applicable.",
        "applicable": "Applicable! Relevant.",
        "relevant": "Relevant! Related.",
        "related": "Related! Connected.",
        "connected": "Connected! Linked.",
        "linked": "Linked! Associated.",
        "associated": "Associated! Related.",
        "related": "Related! Connected.",
        "connected": "Connected! Attached.",
        "attached": "Attached! Joined.",
        "joined": "Joined! United.",
        "united": "United! Together.",
        "together": "Together! Unified.",
        "unified": "Unified! Combined.",
        "combined": "Combined! Merged.",
        "merged": "Merged! Integrated.",
        "integrated": "Integrated! Unified.",
        "unified": "Unified! Cohesive.",
        "cohesive": "Cohesive! Consistent.",
        "consistent": "Consistent! Uniform.",
        "uniform": "Uniform! Even.",
        "even": "Even! Level.",
        "level": "Level! Balanced.",
        "balanced": "Balanced! Equal.",
        "equal": "Equal! Fair.",
        "fair": "Fair! Just.",
        "just": "Just! Righteous.",
        "righteous": "Righteous! Moral.",
        "moral": "Moral! Ethical.",
        "ethical": "Ethical! Principled.",
        "principled": "Principled! Honorable.",
        "honorable": "Honorable! Dignified.",
        "dignified": "Dignified! Noble.",
        "noble": "Noble! Exalted.",
        "exalted": "Exalted! Elevated.",
        "elevated": "Elevated! Superior.",
        "superior": "Superior! Excellent.",
        "excellent": "Excellent! Outstanding.",
        "outstanding": "Outstanding! Exceptional.",
        "exceptional": "Exceptional! Remarkable.",
        "remarkable": "Remarkable! Extraordinary.",
        "extraordinary": "Extraordinary! Amazing.",
        "amazing": "Amazing! Astonishing.",
        "astonishing": "Astonishing! Stunning.",
        "stunning": "Stunning! Impressive.",
        "impressive": "Impressive! Striking.",
        "striking": "Striking! Notable.",
        "notable": "Notable! Significant.",
        "significant": "Significant! Meaningful.",
        "meaningful": "Meaningful! Purposeful.",
        "purposeful": "Purposeful! Intentional.",
        "intentional": "Intentional! Deliberate.",
        "deliberate": "Deliberate! Planned.",
        "planned": "Planned! Organized.",
        "organized": "Organized! Structured.",
        "structured": "Structured! Systematic.",
        "systematic": "Systematic! Methodical.",
        "methodical": "Methodical! Orderly.",
        "orderly": "Orderly! Neat.",
        "neat": "Neat! Tidy.",
        "tidy": "Tidy! Clean.",
        "clean": "Clean! Pure.",
        "pure": "Pure! Unadulterated.",
        "unadulterated": "Unadulterated! Genuine.",
        "genuine": "Genuine! Authentic.",
        "authentic": "Authentic! Real.",
        "real": "Real! True.",
        "true": "True! Veritable.",
        "veritable": "Veritable! Actual.",
        "actual": "Actual! Factual.",
        "factual": "Factual! Real.",
        "real": "Real! Concrete.",
        "concrete": "Concrete! Tangible.",
        "tangible": "Tangible! Physical.",
        "physical": "Physical! Material.",
        "material": "Material! Substantial.",
        "substantial": "Substantial! Solid.",
        "solid": "Solid! Firm.",
        "firm": "Firm! Strong.",
        "strong": "Strong! Powerful.",
        "powerful": "Powerful! Mighty.",
        "mighty": "Mighty! Potent.",
        "potent": "Potent! Effective.",
        "effective": "Effective! Efficient.",
        "efficient": "Efficient! Productive.",
        "productive": "Productive! Fruitful.",
        "fruitful": "Fruitful! Successful.",
        "successful": "Successful! Prosperous.",
        "prosperous": "Prosperous! Thriving.",
        "thriving": "Thriving! Flourishing.",
        "flourishing": "Flourishing! Blooming.",
        "blooming": "Blooming! Growing.",
        "growing": "Growing! Expanding.",
        "expanding": "Expanding! Increasing.",
        "increasing": "Increasing! Rising.",
        "rising": "Rising! Ascending.",
        "ascending": "Ascending! Climbing.",
        "climbing": "Climbing! Mounting.",
        "mounting": "Mounting! Growing.",
        "growing": "Growing! Developing.",
        "developing": "Developing! Evolving.",
        "evolving": "Evolving! Changing.",
        "changing": "Changing! Transforming.",
        "transforming": "Transforming! Metamorphosing.",
        "metamorphosing": "Metamorphosing! Transmuting.",
        "transmuting": "Transmuting! Converting.",
        "converting": "Converting! Changing.",
        "changing": "Changing! Altering.",
        "altering": "Altering! Modifying.",
        "modifying": "Modifying! Adapting.",
        "adapting": "Adapting! Adjusting.",
        "adjusting": "Adjusting! Tuning.",
        "tuning": "Tuning! Calibrating.",
        "calibrating": "Calibrating! Fine-tuning.",
        "fine-tuning": "Fine-tuning! Refining.",
        "refining": "Refining! Perfecting.",
        "perfecting": "Perfecting! Improving.",
        "improving": "Improving! Enhancing.",
        "enhancing": "Enhancing! Bettering.",
        "bettering": "Bettering! Advancing.",
        "advancing": "Advancing! Progressing.",
        "progressing": "Progressing! Proceeding.",
        "proceeding": "Proceeding! Continuing.",
        "continuing": "Continuing! Persisting.",
        "persisting": "Persisting! Enduring.",
        "enduring": "Enduring! Lasting.",
        "lasting": "Lasting! Permanent.",
        "permanent": "Permanent! Eternal.",
        "eternal": "Eternal! Timeless.",
        "timeless": "Timeless! Immortal.",
        "immortal": "Immortal! Undying.",
        "undying": "Undying! Everlasting.",
        "everlasting": "Everlasting! Perpetual.",
        "perpetual": "Perpetual! Continuous.",
        "continuous": "Continuous! Uninterrupted.",
        "uninterrupted": "Uninterrupted! Constant.",
        "constant": "Constant! Steady.",
        "steady": "Steady! Stable.",
        "stable": "Stable! Firm.",
        "firm": "Firm! Solid.",
        "solid": "Solid! Strong.",
        "strong": "Strong! Robust.",
        "robust": "Robust! Sturdy.",
        "sturdy": "Sturdy! Durable.",
        "durable": "Durable! Long-lasting.",
        "long-lasting": "Long-lasting! Enduring.",
        "enduring": "Enduring! Resilient.",
        "resilient": "Resilient! Tough.",
        "tough": "Tough! Hardy.",
        "hardy": "Hardy! Rugged.",
        "rugged": "Rugged! Tough.",
        "tough": "Tough! Strong.",
        "strong": "Strong! Powerful.",
        "powerful": "Powerful! Mighty.",
        "mighty": "Mighty! Forceful.",
        "forceful": "Forceful! Strong.",
        "strong": "Strong! Intense.",
        "intense": "Intense! Powerful.",
        "powerful": "Powerful! Vigorous.",
        "vigorous": "Vigorous! Energetic.",
        "energetic": "Energetic! Dynamic.",
        "dynamic": "Dynamic! Lively.",
        "lively": "Lively! Vivacious.",
        "vivacious": "Vivacious! Spirited.",
        "spirited": "Spirited! Animated.",
        "animated": "Animated! Enthusiastic.",
        "enthusiastic": "Enthusiastic! Eager.",
        "eager": "Eager! Keen.",
        "keen": "Keen! Ardent.",
        "ardent": "Ardent! Passionate.",
        "passionate": "Passionate! Fervent.",
        "fervent": "Fervent! Intense.",
        "intense": "Intense! Zealous.",
        "zealous": "Zealous! Devoted.",
        "devoted": "Devoted! Dedicated.",
        "dedicated": "Dedicated! Committed.",
        "committed": "Committed! Loyal.",
        "loyal": "Loyal! Faithful.",
        "faithful": "Faithful! True.",
        "true": "True! Loyal.",
        "loyal": "Loyal! Steadfast.",
        "steadfast": "Steadfast! Unwavering.",
        "unwavering": "Unwavering! Resolute.",
        "resolute": "Resolute! Determined.",
        "determined": "Determined! Decided.",
        "decided": "Decided! Resolved.",
        "resolved": "Resolved! Settled.",
        "settled": "Settled! Fixed.",
        "fixed": "Fixed! Established.",
        "established": "Established! Founded.",
        "founded": "Founded! Created.",
        "created": "Created! Made.",
        "made": "Made! Produced.",
        "produced": "Produced! Generated.",
        "generated": "Generated! Created.",
        "created": "Created! Formed.",
        "formed": "Formed! Shaped.",
        "shaped": "Shaped! Molded.",
        "molded": "Molded! Fashioned.",
        "fashioned": "Fashioned! Designed.",
        "designed": "Designed! Planned.",
        "planned": "Planned! Intended.",
        "intended": "Intended! Meant.",
        "meant": "Meant! Purposed.",
        "purposed": "Purposed! Aimed.",
        "aimed": "Aimed! Directed.",
        "directed": "Directed! Guided.",
        "guided": "Guided! Led.",
        "led": "Led! Conducted.",
        "conducted": "Conducted! Managed.",
        "managed": "Managed! Handled.",
        "handled": "Handled! Dealt.",
        "dealt": "Dealt! Managed.",
        "managed": "Managed! Administered.",
        "administered": "Administered! Supervised.",
        "supervised": "Supervised! Oversaw.",
        "oversaw": "Oversaw! Controlled.",
        "controlled": "Controlled! Regulated.",
        "regulated": "Regulated! Governed.",
        "governed": "Governed! Ruled.",
        "ruled": "Ruled! Commanded.",
        "commanded": "Commanded! Directed.",
        "directed": "Directed! Ordered.",
        "ordered": "Ordered! Arranged.",
        "arranged": "Arranged! Organized.",
        "organized": "Organized! Structured.",
        "structured": "Structured! Systematized.",
        "systematized": "Systematized! Methodized.",
        "methodized": "Methodized! Rationalized.",
        "rationalized": "Rationalized! Justified.",
        "justified": "Justified! Warranted.",
        "warranted": "Warranted! Deserved.",
        "deserved": "Deserved! Earned.",
        "earned": "Earned! Merited.",
        "merited": "Merited! Deserved.",
        "deserved": "Deserved! Worthy.",
        "worthy": "Worthy! Deserving.",
        "deserving": "Deserving! Meritorious.",
        "meritorious": "Meritorious! Commendable.",
        "commendable": "Commendable! Praiseworthy.",
        "praiseworthy": "Praiseworthy! Laudable.",
        "laudable": "Laudable! Admirable.",
        "admirable": "Admirable! Excellent.",
        "excellent": "Excellent! Superb.",
        "superb": "Superb! Magnificent.",
        "magnificent": "Magnificent! Splendid.",
        "splendid": "Splendid! Glorious.",
        "glorious": "Glorious! Grand.",
        "grand": "Grand! Majestic.",
        "majestic": "Majestic! Impressive.",
        "impressive": "Impressive! Awesome.",
        "awesome": "Awesome! Fantastic.",
        "fantastic": "Fantastic! Wonderful.",
        "wonderful": "Wonderful! Marvelous.",
        "marvelous": "Marvelous! Terrific.",
        "terrific": "Terrific! Great.",
        "great": "Great! Super.",
        "super": "Super! Excellent.",
        "excellent": "Excellent! Fine.",
        "fine": "Fine! Good.",
        "good": "Good! Nice.",
        "nice": "Nice! Pleasant.",
        "pleasant": "Pleasant! Agreeable.",
        "agreeable": "Agreeable! Amiable.",
        "amiable": "Amiable! Friendly.",
        "friendly": "Friendly! Cordial.",
        "cordial": "Cordial! Warm.",
        "warm": "Warm! Affectionate.",
        "affectionate": "Affectionate! Loving.",
        "loving": "Loving! Caring.",
        "caring": "Caring! Kind.",
        "kind": "Kind! Benevolent.",
        "benevolent": "Benevolent! Compassionate.",
        "compassionate": "Compassionate! Sympathetic.",
        "sympathetic": "Sympathetic! Empathetic.",
        "empathetic": "Empathetic! Understanding.",
        "understanding": "Understanding! Comprehending.",
        "comprehending": "Comprehending! Grasping.",
        "grasping": "Grasping! Apprehending.",
        "apprehending": "Apprehending! Realizing.",
        "realizing": "Realizing! Understanding.",
        "understanding": "Understanding! Knowing.",
        "knowing": "Knowing! Aware.",
        "aware": "Aware! Conscious.",
        "conscious": "Conscious! Cognizant.",
        "cognizant": "Cognizant! Mindful.",
        "mindful": "Mindful! Attentive.",
        "attentive": "Attentive! Observant.",
        "observant": "Observant! Perceptive.",
        "perceptive": "Perceptive! Insightful.",
        "insightful": "Insightful! Discerning.",
        "discerning": "Discerning! Discriminating.",
        "discriminating": "Discriminating! Selective.",
        "selective": "Selective! Choosy.",
        "choosy": "Choosy! Picky.",
        "picky": "Picky! Fussy.",
        "fussy": "Fussy! Particular.",
        "particular": "Particular! Specific.",
        "specific": "Specific! Precise.",
        "precise": "Precise! Exact.",
        "exact": "Exact! Accurate.",
        "accurate": "Accurate! Correct.",
        "correct": "Correct! Right.",
        "right": "Right! Proper.",
        "proper": "Proper! Appropriate.",
        "appropriate": "Appropriate! Suitable.",
        "suitable": "Suitable! Fitting.",
        "fitting": "Fitting! Apt.",
        "apt": "Apt! Relevant.",
        "relevant": "Relevant! Pertinent.",
        "pertinent": "Pertinent! Applicable.",
        "applicable": "Applicable! Relevant.",
        "relevant": "Relevant! Related.",
        "related": "Related! Connected.",
        "connected": "Connected! Linked.",
        "linked": "Linked! Associated.",
        "associated": "Associated! Related.",
        "related": "Related! Connected.",
        "connected": "Connected! Attached.",
        "attached": "Attached! Joined.",
        "joined": "Joined! United.",
        "united": "United! Together.",
        "together": "Together! Unified.",
        "unified": "Unified! Combined.",
        "combined": "Combined! Merged.",
        "merged": "Merged! Integrated.",
        "integrated": "Integrated! Unified.",
        "unified": "Unified! Cohesive.",
        "cohesive": "Cohesive! Consistent.",
        "consistent": "Consistent! Uniform.",
        "uniform": "Uniform! Even.",
        "even": "Even! Level.",
        "level": "Level! Balanced.",
        "balanced": "Balanced! Equal.",
        "equal": "Equal! Fair.",
        "fair": "Fair! Just.",
        "just": "Just! Righteous.",
        "righteous": "Righteous! Moral.",
        "moral": "Moral! Ethical.",
        "ethical": "Ethical! Principled.",
        "principled": "Principled! Honorable.",
        "honorable": "Honorable! Dignified.",
        "dignified": "Dignified! Noble.",
        "noble": "Noble! Exalted.",
        "exalted": "Exalted! Elevated.",
    }

    # Check if user_input is in personality_responses
    if user_input_lower in personality_responses:
        response = personality_responses[user_input_lower]
    else:
        response = "I'm not sure how to respond to that. Can you rephrase?"

    # Format the response using personality
    formatted_response = personality.format_response(response)
    return formatted_response
